title: matklad
description: >
  Yet another programming blog by Aleksey Kladov aka matklad.
baseurl: ""
url: "https://matklad.github.io/"
github_username: matklad

plugins:
- jekyll-asciidoc
- jekyll-redirect-from

asciidoctor:
  attributes:
    - icons=font
    - source-highlighter=rouge
    - rouge-style=github
    - stylesdir=css
