title: matklad
description: >
  Yet another programming blog by Aleksey Kladov aka matklad.
baseurl: ""
url: "https://matklad.github.io/"
github_username: matklad

plugins:
- jekyll-asciidoc

asciidoctor:
  attributes:
    - icons=font
    - source-highlighter=pygments
    - stylesdir=css
    - pygments-css=class
    - pygments-stylesheet=asciidoctor-pygments.css
