title: matklad
description: >
  Yet another programming blog by Aleksey Kladov aka matklad.
baseurl: ""
url: "https://matklad.github.io/"
github_username: matklad

author: Aleksey Kladov

plugins:
- jekyll-asciidoc
- jekyll-redirect-from
- jekyll-feed

asciidoctor:
  attributes:
    - icons=font
    - source-highlighter=rouge
    - source-linenums-option=_
    - sectanchors=_
    - experimental=_
    - rouge-style=github
    - stylesdir=css
