# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: matklad
email: aleksey.kladov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yet another programming blog by Aleksey Kladov aka matklad.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://matklad.github.io/" # the base hostname & protocol for your site
github_username:  matklad

# Build settings
markdown: kramdown
kramdown:
#  input: GFM
  syntax_highlighter: rouge
